server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /politicasdeprivacidad {
        try_files /politicasdeprivacidad/index.html =404;
    }

    location = /terms {
        try_files /terms/index.html =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
